name: Code Analysis on Pull

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install Packages
        run: poetry install

      - name: Flake8 (Linter)
        run: poetry run flake8
      
      - name: isort (Import Sorter)
        run: poetry run isort
  
      - name: Black (Code Formatter)
        run: poetry run black

      - name: Check for changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
    
      - name: Commit and Push Changes
        if: steps.changes.outputs.changed == 1
        run: |
          git config user.name code-analysis-action
          git config user.email github-actions@github.com
          git commit -a -m "Changes by Code Analysis Action" --no-verify
          git push
